name: Build and Deploy SDK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v5.1.0
      id: generate-version
      with:
        tag_prefix: "v"
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build
    - name: Publish package
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        arguments: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITVERSION_ASSEMBLYSEMFILEVER: ${{ steps.generate-version.outputs.version }}
    - name: Create tag and push
      run: git tag v${{ steps.generate-version.outputs.version }} && git push --tags || echo "tag already exist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
